config/routes.rb
Rails.application.routes.draw do
  ## get 'pages/home' ## replaced with:
  root 'pages#home'

  get 'about' => 'pages#about'
  get 'contactus' => 'pages#contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Omrails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "Home", root_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Contact Us", contactus_path %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>ABOUT Page</h1>
<p> secondary page </p>

app/views/pages/contact.html.erb
<h1>Contact page</h1>
<p>..third page..</p>

app/views/pages/home.html.erb
<h1>Test rails project.</h1>
<p>details..</p>